# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# book1 = Book.create([
#   {title: "The Great Gatsby", author: "F. Scott Fitzgerald", genre: "Fiction", image_url: "http://images.rapgenius.com/bfz5ovh9ecolxdr1f3j00fka2.534x800x1.jpg", no_pages: 215, synopsis: "Midwest native Nick Carraway arrives in 1922 New York in search of the American dream. Nick, a would-be writer, moves in next-door to millionaire Jay Gatsby and across the bay from his cousin Daisy (Carey Mulligan) and her philandering husband, Tom. Thus, Nick becomes drawn into the captivating world of the wealthy and -- as he bears witness to their illusions and deceits -- pens a tale of impossible love, dreams, and tragedy.", condition: "Good", user_id: 1},
#
#   {title: "The Great Gatsby", author: "F. Scott Fitzgerald", genre: "Fiction", image_url: "http://images.rapgenius.com/bfz5ovh9ecolxdr1f3j00fka2.534x800x1.jpg", no_pages: 215, synopsis: "Midwest native Nick Carraway arrives in 1922 New York in search of the American dream. Nick, a would-be writer, moves in next-door to millionaire Jay Gatsby and across the bay from his cousin Daisy (Carey Mulligan) and her philandering husband, Tom. Thus, Nick becomes drawn into the captivating world of the wealthy and -- as he bears witness to their illusions and deceits -- pens a tale of impossible love, dreams, and tragedy.", condition: "Good", user_id: 1},
#
#   {title: "The Great Gatsby", author: "F. Scott Fitzgerald", genre: "Fiction", image_url: "http://images.rapgenius.com/bfz5ovh9ecolxdr1f3j00fka2.534x800x1.jpg", no_pages: 215, synopsis: "Midwest native Nick Carraway arrives in 1922 New York in search of the American dream. Nick, a would-be writer, moves in next-door to millionaire Jay Gatsby and across the bay from his cousin Daisy (Carey Mulligan) and her philandering husband, Tom. Thus, Nick becomes drawn into the captivating world of the wealthy and -- as he bears witness to their illusions and deceits -- pens a tale of impossible love, dreams, and tragedy.", condition: "Good", user_id: 1}
#
# ])


@user1 = User.create(email: "what_the1@yahoo.com", password: "password", password_confirmation: "password" , username: "Marky Mark", profile_photo_url: "http://a4.files.biography.com/image/upload/c_fit,cs_srgb,dpr_1.0,h_1200,q_80,w_1200/MTE5NDg0MDU1MTUzNTA5OTAz.jpg", about: "Hi I'm Mark")
@user1.save!

@user2 = User.create(email: "what_the2@yahoo.com", password: "password", password_confirmation: "password" , username: "Franky H", profile_photo_url: "http://erikhanberg.com/wp-content/uploads/2013/01/itzk450.jpeg", about: "Hi I'm Frank")
@user2.save!

@user3 = User.create(email: "what_the3@yahoo.com", password: "password", password_confirmation: "password" , username: "Capot the GOAT", profile_photo_url: "https://milkcrater.com/wp-content/uploads/2015/10/Capote.jpg", about: "Hi I'm Truman")
@user3.save!

@user4 = User.create(email: "what_the4@yahoo.com", password: "password", password_confirmation: "password" , username: "Ernesto", profile_photo_url: "https://upload.wikimedia.org/wikipedia/commons/2/28/ErnestHemingway.jpg", about: "Hi I'm Ernest")
@user4.save!

@user5 = User.create(email: "what_the5@yahoo.com", password: "password", password_confirmation: "password" , username: "Johnny S", profile_photo_url: "http://www.notablebiographies.com/images/uewb_09_img0658.jpg", about: "Hi I'm John")
@user5.save!

@user7 = User.create(email: "what_the6@yahoo.com", password: "password", password_confirmation: "password" , username: "The Joyce Man", profile_photo_url: "http://cps-static.rovicorp.com/3/JPG_400/MI0002/861/MI0002861493.jpg?partner=allrovi.com", about: "Hi I'm James")
@user7.save!

@user1.books.create(title: "The Great Gatsby" , author: "F. Scott Fitzgerald", genre: "Fiction", image_url: "http://images.rapgenius.com/bfz5ovh9ecolxdr1f3j00fka2.534x800x1.jpg", no_pages: 321, condition: "Good" , synopsis:"Midwest native Nick Carraway arrives in 1922 New York in search of the American dream. Nick, a would-be writer, moves in next-door to millionaire Jay Gatsby and across the bay from his cousin Daisy (Carey Mulligan) and her philandering husband, Tom. Thus, Nick becomes drawn into the captivating world of the wealthy and -- as he bears witness to their illusions and deceits -- pens a tale of impossible love, dreams, and tragedy.")

@user1.books.create(title: "Brave New World" , author: "Aldous Huxley", genre: "Fiction", image_url: "https://upload.wikimedia.org/wikipedia/en/6/62/BraveNewWorld_FirstEdition.jpg", no_pages: 255, condition: "Good" , synopsis:"The novel opens in the Central London Hatching and Conditioning Centre, where the Director of the Hatchery and one of his assistants, Henry Foster, are giving a tour to a group of boys. The boys learn about the Bokanovsky and Podsnap Processes that allow the Hatchery to produce thousands of nearly identical human embryos. During the gestation period the embryos travel in bottles along a conveyor belt through a factorylike building, and are conditioned to belong to one of five castes: Alpha, Beta, Gamma, Delta, or Epsilon. The Alpha embryos are destined to become the leaders and thinkers of the World State. Each of the succeeding castes is conditioned to be slightly less physically and intellectually impressive. The Epsilons, stunted and stupefied by oxygen deprivation and chemical treatments, are destined to perform menial labor. Lenina Crowne, an employee at the factory, describes to the boys how she vaccinates embryos destined for tropical climates.")

@user1.books.create(title: "The Sound and the Fury" , author: "William Faulkner", genre: "Fiction", image_url: "https://upload.wikimedia.org/wikipedia/en/thumb/e/e3/TheSoundAndTheFuryCover.jpg/220px-TheSoundAndTheFuryCover.jpg", no_pages: 378, condition: "Good" , synopsis:"The Compson family is falling apart. The kids run wild, the mother locks herself in her bedroom with a hot water bottle and her Bible, and the father locks himself in the den with a nice big bottle of whiskey. In other words, life isn’t exactly the sunniest. Not to worry, though: it can always get worse.")

@user2.books.create(title: "1984" , author: "George Orwell", genre: "Fiction", image_url: "https://lightlit.files.wordpress.com/2014/07/1984_by_alcook-d4z39dh.jpg", no_pages: 221, condition: "Good" , synopsis:"Winston Smith is a low-ranking member of the ruling Party in London, in the nation of Oceania. Everywhere Winston goes, even his own home, the Party watches him through telescreens; everywhere he looks he sees the face of the Party’s seemingly omniscient leader, a figure known only as Big Brother. The Party controls everything in Oceania, even the people’s history and language. Currently, the Party is forcing the implementation of an invented language called Newspeak, which attempts to prevent political rebellion by eliminating all words related to it. Even thinking rebellious thoughts is illegal. Such thoughtcrime is, in fact, the worst of all crimes.")

@user2.books.create(title: "To The Lighthouse" , author: "Virginia Woolf", genre: "Fiction", image_url: "http://d.gr-assets.com/books/1346239665l/59716.jpg", no_pages: 456, condition: "Good" , synopsis:"“The Window” opens just before the start of World War I. Mr. Ramsay and Mrs. Ramsay bring their eight children to their summer home in the Hebrides (a group of islands west of Scotland). Across the bay from their house stands a large lighthouse. Six-year-old James Ramsay wants desperately to go to the lighthouse, and Mrs. Ramsay tells him that they will go the next day if the weather permits. James reacts gleefully, but Mr. Ramsay tells him coldly that the weather looks to be foul. James resents his father and believes that he enjoys being cruel to James and his siblings.")

@user2.books.create(title: "Catch-22" , author: "Joseph Heller", genre: "Fiction", image_url: "https://upload.wikimedia.org/wikipedia/en/9/99/Catch22.jpg", no_pages: 410, condition: "Good" , synopsis:"Catch-22 follows Captain John Yossarian in his exploits as a bombardier (that is, a member of a fighter plane crew that is in charge of aiming and releasing bombs) in the U.S. Air Force during World War II. Yossarian has one wish: to survive the madness of war. He's convinced that everyone is trying to kill him, which is understandable seeing as how he's fighting in a war, where everyone really is trying to kill one another. Yossarian has to survive the dangerous combat missions he flies, while Colonel Cathcart continues to increase the number of missions his men must complete.")

@user3.books.create(title: "Slaughterhouse-Five" , author: "Kurt Vonnegut", genre: "Fiction", image_url: "http://7summitsproject.com/wp-content/uploads/2015/06/Slaughterhouse-Five.jpg", no_pages: 210, condition: "Good" , synopsis:"Billy Pilgrim is born in 1922 and grows up in Ilium, New York. A funny-looking, weak youth, he does reasonably well in high school, enrolls in night classes at the Ilium School of Optometry, and is drafted into the army during World War II. He trains as a chaplain’s assistant in South Carolina, where an umpire officiates during practice battles and announces who survives and who dies before they all sit down to lunch together. Billy’s father dies in a hunting accident shortly before Billy ships overseas to join an infantry regiment in Luxembourg. Billy is thrown into the Battle of the Bulge in Belgium and is immediately taken prisoner behind German lines. Just before his capture, he experiences his first incident of time—shifting: he sees the entirety of his life, from beginning to end, in one sweep.")

@user3.books.create(title: "The Lord of the Rings" , author: "J. R. R. Tolkien", genre: "Fiction", image_url: "http://cdn3.vox-cdn.com/assets/4242181/lord_of_the_rings_book_cover_by_mrstingyjr-d5vwgct.jpg", no_pages: 510, condition: "Good" , synopsis:"When the eccentric hobbit Bilbo Baggins leaves his home in the Shire, he gives his greatest treasure to his heir Frodo: a magic ring that makes its wearer invisible. Because of the difficulty Bilbo has in giving the ring away, his friend the wizard Gandalf the Grey suspects that the ring is more than it appears. Some years later, Gandalf reveals to Frodo that the ring is in fact the One Ring, forged by Sauron the Dark Lord thousands of years before to enable him to dominate and enslave all of Middle-earth. Gandalf tells Frodo that the Ring must be destroyed to defeat Sauron's evil, but he also warns him that the Enemy has learned of the Ring's whereabouts from the creature Gollum and will seek to find it and kill its bearer. Despite the danger and hopelessness of the quest, Frodo accepts the burden and resolves to take the Ring to the safety of the elven stronghold of Rivendell.")

@user3.books.create(title: "To Kill A Mockingbird" , author: "Harper Lee", genre: "Fiction", image_url: "http://ecx.images-amazon.com/images/I/51grMGCKivL._SY344_BO1,204,203,200_.jpg", no_pages: 259, condition: "Fair" , synopsis:"Scout Finch lives with her brother, Jem, and their widowed father, Atticus, in the sleepy Alabama town of Maycomb. Maycomb is suffering through the Great Depression, but Atticus is a prominent lawyer and the Finch family is reasonably well off in comparison to the rest of society. One summer, Jem and Scout befriend a boy named Dill, who has come to live in their neighborhood for the summer, and the trio acts out stories together. Eventually, Dill becomes fascinated with the spooky house on their street called the Radley Place. The house is owned by Mr. Nathan Radley, whose brother, Arthur (nicknamed Boo), has lived there for years without venturing outside.")

@user4.books.create(title: "Ulysses" , author: "James Joyce", genre: "Fiction", image_url: "https://upload.wikimedia.org/wikipedia/commons/a/ab/JoyceUlysses2.jpg", no_pages: 551, condition: "Fair" , synopsis:"Stephen Dedalus spends the early morning hours of June 16, 1904, remaining aloof from his mocking friend, Buck Mulligan, and Buck’s English acquaintance, Haines. As Stephen leaves for work, Buck orders him to leave the house key and meet them at the pub at 12:30. Stephen resents Buck.")

@user4.books.create(title: "Dune" , author: "Frank Herbery", genre: "Fiction", image_url: "https://cf.geekdo-images.com/images/pic279251.jpg", no_pages: 691, condition: "Fair" , synopsis:"Dune is based on a complex imagined society set roughly 20,000 years in the future. The setting is the year 10,191, and human beings have spread out and colonized planets throughout the universe. On the planet Caladan, Duke Leto of the House of Atreides is preparing to leave for his new position as the governor of Arrakis, a desert planet with valuable resources of melange, a spice drug that is extremely popular with wealthy people. Leto and his family, including his concubine, Jessica, and his son, Paul, suspect a trap by their rivals, the Harkonnens, led by Baron Harkonnen. Leto decides to settle on Arrakis because of its rich supplies of melange, despite warnings from his men, including his adviser, Thufir Hawat, and his master-of-arms, Gurney Halleck.")

@user4.books.create(title: "Stranger In a Strange Land" , author: "Robert Heinlein", genre: "Fiction", image_url: "http://d.gr-assets.com/books/1156897088l/350.jpg", no_pages: 429, condition: "Fair" , synopsis:"Humankind sends its first human expedition to Mars. The spaceship's crew arrives on the planet and are never heard from again. Twenty-five years later, another mission is sent, and the child of two of the first ship's crewmembers, who has been born on Mars and raised by the peculiar Martian race, is discovered and brought back to Earth. Because of various legal precedents, Valentine Michael Smith, the Man from Mars, is the inheritor to a vast fortune, and because of another precedent known as the Larkin Decision, Mike has a claim to legal ownership of the planet Mars. Therefore he has the potential to be massively influential in matters of Earth politics, and he is kept under close guard at a hospital by the leader of Earth's government, Secretary General Joseph Douglas. In the hospital, Mike slowly teaches his body to adapt to the Earth's atmosphere and he begins learning Earth culture and language, which differ enormously from Martian ways of thought.")

@user5.books.create(title: "The Catcher In The Rye" , author: "J.D. Salinger", genre: "Fiction", image_url: "https://upload.wikimedia.org/wikipedia/en/3/32/Rye_catcher.jpg", no_pages: 309, condition: "Fair" , synopsis:"The Catcher in the Rye is set around the 1950s and is narrated by a young man named Holden Caulfield. Holden is not specific about his location while he’s telling the story, but he makes it clear that he is undergoing treatment in a mental hospital or sanatorium. The events he narrates take place in the few days between the end of the fall school term and Christmas, when Holden is sixteen years old.")

@user5.books.create(title: "On The Road" , author: "Jack Keuroac", genre: "Fiction", image_url: "http://youngtopublishing.com/wp-content/uploads/2014/06/on_the_road.large_.jpg", no_pages: 283, condition: "Good" , synopsis:"In the winter of 1947, the reckless and joyous Dean Moriarty, fresh out of another stint in jail and newly married, comes to New York City and meets Sal Paradise, a young writer with an intellectual group of friends, among them the poet Carlo Marx. Dean fascinates Sal, and their friendship begins three years of restless journeys back and forth across the country. With a combination of bus rides and adventurous hitchhiking escapades, Sal goes to his much-dreamed-of west to join Dean and more friends in Denver, and then continues west by himself, working as a fieldworker in California for awhile, among other things. The next year, Dean comes east to Sal again, foiling Sal's stable life once more, and they drive west together, with more crazy adventures on the way at Bull Lee's in New Orleans, ending in San Francisco this time. The winter after that, Sal goes to Dean, and they blaze across the country together in friendly fashion, and Dean settles in New York for awhile. In the spring, Sal goes to Denver alone, but Dean soon joins him and they go south all the way to Mexico City this time.")

@user5.books.create(title: "The Hitchhiker's Guide to the Galaxy" , author: "Douglas Adams", genre: "Fiction", image_url: "https://upload.wikimedia.org/wikipedia/commons/a/ab/JoyceUlysses2.jpg", no_pages: 489, condition: "Good" , synopsis:"What if the world ended tomorrow—where would you get your favorite drink? That's the situation faced by Arthur Dent, totally normal English guy (favorite drink: tea). Arthur isn't a hero—he's actually pretty boring—but after Earth is destroyed, Arthur is thrust into a series of crazy adventures that he's totally unprepared for. That might sound like a tragedy (after all, Earth is where our favorite food is made), but take it from us: it's totally a comedy. Lots of comedies begin with the destruction of Earth, right?")

@user7.books.create(title: "A Clockwork Orange" , author: "Anthony Burgess", genre: "Fiction", image_url: "http://richflaherty.com/clockwork/images/bcover1.jpg", no_pages: 329, condition: "Fair" , synopsis:"A Clockwork Orange takes place in a futuristic city governed by a repressive, totalitarian super-State. In this society, ordinary citizens have fallen into a passive stupor of complacency, blind to the insidious growth of a rampant, violent youth culture. The protagonist of the story is Alex, a fifteen-year-old boy who narrates in a teenage slang called nadsat, which incorporates elements of Russian and Cockney English. Alex leads a small gang of teenage criminals—Dim, Pete, and Georgie—through the streets, robbing and beating men and raping women. Alex and his friends spend the rest of their time at the Korova Milkbar, an establishment that serves milk laced with drugs, and a bar called the Duke of New York.")

@user7.books.create(title: "Ender's Game" , author: "Orson Scott Card", genre: "Fiction", image_url: "http://d.gr-assets.com/books/1408303130l/375802.jpg", no_pages: 325, condition: "Fair" , synopsis:"Ender Wiggin, the third in a family of child geniuses, is selected by international military forces to save the world from destruction. Before being chosen Ender wears a unique monitor that allows the heads of the military to see things as Ender does. Ender's brother Peter and his sister Valentine also wore this monitor, although neither was selected, nor did they have it for as long as Ender, and Peter will never forgive Ender for this. Peter hates Ender, and even when the monitor is taken out it does nothing to decrease Peter's anger. The same is true of Ender's schoolmates, and he is forced into brutally beating the leader of a gang of bullies in order to protect himself. Although Valentine tries to protect Ender from Peter, he is only saved from his brother when Colonel Graff of the International Fleet comes to take Ender away to Battle School. Ender leaves behind Valentine, who loves him, in order to help save the world from the buggers.")

@user7.books.create(title: "A Farewell to Arms" , author: "Ernest Hemingway", genre: "Fiction", image_url: "http://ecx.images-amazon.com/images/I/514omBy1BgL._SY344_BO1,204,203,200_.jpg", no_pages: 284, condition: "Fair" , synopsis:"Lieutenant Frederic Henry is a young American ambulance driver serving in the Italian army during World War I. At the beginning of the novel, the war is winding down with the onset of winter, and Henry arranges to tour Italy. The following spring, upon his return to the front, Henry meets Catherine Barkley, an English nurse’s aide at the nearby British hospital and the love interest of his friend Rinaldi. Rinaldi, however, quickly fades from the picture as Catherine and Henry become involved in an elaborate game of seduction. Grieving the recent death of her fiancé, Catherine longs for love so deeply that she will settle for the illusion of it. Her passion, even though pretended, wakens a desire for emotional interaction in Henry, whom the war has left coolly detached and numb.")
